on:
  push:
    branches:
    - main

jobs:
  versions:
    runs-on: ubuntu-24.04
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
      matrix: ${{ steps.versions.outputs.matrix }}
    steps:
    - id: checkout
      uses: actions/checkout@v2
    - id: filter
      uses: dorny/paths-filter@v2
      with:
        base: ${{ github.ref }}
        list-files: shell
        filters: |
          changed:
            added|modified: 'path-filter/**'
    - id: versions
      if: steps.filter.outputs.changed == 'true'
      run: |
        VERS=()
        PATHS=(${{ steps.filter.outputs.changed_files }})
        for p in "${PATHS[@]}" ; do
          IFS='/' read -r -a parts <<< "$p"
          VERS+=("${parts[1]}")
        done

        MATRIX=$(echo "${VERS[@]}" | tr ' ' '\n' | sort -u | jq -R | jq -sc '{version: .}')
        echo "PATHS: ${PATHS[@]}"
        echo "PATHS: ${VERS[@]}"
        echo "MATRIX: ${MATRIX}"
        echo ::set-output name=matrix::${MATRIX}

  print:
    runs-on: ubuntu-24.04
    needs: versions
    if: ${{ needs.versions.outputs.changed == 'true' }}
    strategy:
      matrix: ${{ fromJson(needs.versions.outputs.matrix) }}
    steps:
    - id: checkout
      uses: actions/checkout@v2
    - id: echo
      run: |
        echo "Processing: ${{ matrix.version }}"
